version: '3.8'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "3002:8000"
    volumes:
      - "./database:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal