Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.

Resources:
  coursesTable:
    Metadata:
      'aws:copilot:description': 'An Amazon DynamoDB table for coursesTable'
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Env}-coursesTable
      AttributeDefinitions:
        - AttributeName: courseId
          AttributeType: "S"
        - AttributeName: subKey
          AttributeType: "S"
        - AttributeName: memberId
          AttributeType: "S"
        - AttributeName: creatorId
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: courseId
          KeyType: HASH
        - AttributeName: subKey
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: membership
          KeySchema: 
            - AttributeName: memberId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: userRequests
          KeySchema: 
            - AttributeName: creatorId
              KeyType: HASH
            - AttributeName: courseId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  coursesTableName:
    Description: "The name of this DynamoDB table."
    Value: !Ref coursesTable
    Export: 
      Name: !Sub ${App}-${Env}-coursesTableTableName
  coursesTableDynamoDBTableARN:
    Description: "The ARN of the coursesTable DynamoDB table."
    Value: !GetAtt coursesTable.Arn
    Export: 
      Name: !Sub ${App}-${Env}-coursesTableTableArn
